export const USER_YOUTUBE_COOKIES = [
    {
        "domain": ".youtube.com",
        "expirationDate": 1801361981.380351,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000BAkN_ylCXlPCGYkf8vLtB4Wvj9-A7wwFz4F1fyiqZsWt5qAKnHr2W3IS3qGZxQJim3KJiAACgYKATQSARASFQHGX2MifIcat6c5lZdHtiec4Y7p7BoVAUF8yKpaEvF7kgtvPIrtxc665vir0076"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801562134.941435,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjQBPWEu2f4sm6jYtSu3FQStMJT_TogLyCZoYEGupQ1v4-jXWRK2x55SQaxkOErl-cU2FWPeEAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801361981.382178,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "hKuhXh_BPzd8C_tQ/AvPmuLlfFjVkRnhtp"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801562134.942172,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzUlh2a2Y9pvwMU_oXzoJUKV3UuYVn2-R1saJuhTCcJ7gsbAyoLobEXLRcdJwVjI2AA_J5o"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801361981.38146,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AgjEVDCBScJylKJxm"
    },
    {
        "domain": ".youtube.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "wide",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801361981.382536,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "hKuhXh_BPzd8C_tQ/AvPmuLlfFjVkRnhtp"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801361981.379947,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000BAkN_ylCXlPCGYkf8vLtB4Wvj9-A7wwFz4F1fyiqZsWt5qAK1U4rgshcXSMMfB0M80DK9gACgYKAaESARASFQHGX2Miu9QNPAg-MNQyOB-D-hSHfhoVAUF8yKpZ3UIhb1KOXZjDzDthDAv90076"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801361981.382914,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "hKuhXh_BPzd8C_tQ/AvPmuLlfFjVkRnhtp"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801562134.942355,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzWvrjwDXJS8qQGDxzZ3Nupurfi2-TOcgRroyvVtWhf9l3wPGGDwt14T-jPnQJpw2r0PuKs"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801562134.941783,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjQBPWEu2f4sm6jYtSu3FQStMJT_TogLyCZoYEGupQ1v4-jXWRK2x55SQaxkOErl-cU2FWPeEAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1791173287.913009,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-BUCKET",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "CM8C"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1790124553.105143,
        "hostOnly": false,
        "httpOnly": true,
        "name": "LOGIN_INFO",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AFmmF2swRAIgXVL69SXx9UycEVJNvHN99YgguzmdGZbSL0cl5WpZQuwCIAqf_XMZcC_L9qu1wzhqoIsUuTCk_LGMUxmsnKeEoUpp:QUQ3MjNmdzJfbndtOXdwZTVROFZIdlRwekl6Q3lEcUJ3UG1qNGc0T2RGZWRpemRkUkpaLTFscnBVNEx2OEE4U3gzOE9ScE0xVnV5a0VXdXhyNDFONXFzODNuX01LZlJkWVBYVVpkRW9hSnpLQlMzeUFfa3IydDNMTXlRcW9WU3VxLW5SLUtiaklyTlpNTTVyOFA4RUt4NUhwUHNRU3FneVVR"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1801562057.660995,
        "hostOnly": false,
        "httpOnly": false,
        "name": "PREF",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "tz=Asia.Baghdad&f6=40000000&f7=100&f5=30000&f4=4010000"
    }
];
